### ISSUE TITLE
[수정] 뉴스레터 개인정보보호 동의 클릭 후 신청

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol#1]
웹진 결 뉴스레터 수신자 목록 관련하여 요청드릴 사항이 있어 메일 드립니다.

1.

이메일만 수집하더라도 개인정보에 해당하기 때문에, 뉴스레터 신청 시 개인정보수집에 대한 정보주체의 동의를 받으셔야 합니다.

(관련 법령 해석: 링크 참조)

https://m.kin.naver.com/mobile/qna/detail.nhn?d1Id=6&dirId=60105&docId=328950590

- 본원 홈페이지 오른쪽 하단에 뉴스레터 신청하시면 개인정보 수집 서식이 나옵니다.

참고하셔서 만드시면 될 것 같습니다.

 

2.

수집한 개인정보를 연구소가 아닌 "스티비"라는 업체에 개인정보처리위탁을 맡기고 계시기 때문에 개인정보처리위탁 계약서를 작성하셔야 하며, 해당 사실을 홈페이지에 공지하여야 합니다.

- 김재아 선생님께서 보내신 개인정보처리위탁 계약 관련 내부 메일을 참조하시거나

- 그룹웨어 게시판에 올려둔 내용을 참고하셔서 계약 체결 후 결과를 공유해 주시면 홈페이지 <개인정보처리방침>에 변경사항 공지하겠습니다.

- 사람인 채용사이트를 통한 채용 원서 서류 접수도 인사부서에서 계약을 체결하였습니다.

3.

웹진 결에서 수집된 이메일 정보는 행정안전부 개인정보보호 포털에 등록되며, 해당 사항이 전 국민 공개됩니다.

**Comment by mozodev** [comment]
2. 개인정보 수집 및 이용안내 창 삽입 
- 링크한 구글 문서 내용을 담은 개인정보 수집 및 이용안내 창 삽입이 필요합니다.
 -https://docs.google.com/document/d/1mb3xrr7ZJwMONoOmCpPEqMoXyPij5rElUhjcutSi5IA/edit?usp=sharing
- 한국여성인권진흥원 뉴스레터 신청과 같이 이메을 주소를 기입하면 개인정보 동의 창이 나오는 방식으로 처리하면 좋을 것 같습니다. 
- 참고 : https://www.stop.or.kr/
개인정보 관련해서 연구소에서 빨리 처리하라고 압박을 주네요.  ㅎㅎ

**Comment by woonjjang** [comment]
(05.22) 배포 및 보고

**Comment by woonjjang** [comment]
![웹진결-수정요청](https://user-images.githubusercontent.com/6022883/82994727-9450e480-a03d-11ea-9b8e-bc5b239c1809.PNG)

현재 팝업창 문구에는 [개인정보의 보유 및 이용기간]과, [개인정보처리의 위탁에 관한 사항]이 구별되지 않고 합쳐져 있는데,이 부분을 첨부해드린 '웹진결-수정요청' 파일의 문구내용으로 수정해주시면 된다고 합니다.

(첨부파일은 김재아 선생님께서 보내주신 건데 지난번에 PD님께서 PDF로 보내주신 내용을 캡처해주신 것 같아요.)

**Comment by mozodev** [comment]
서버에 반영했습니다.
