### ISSUE TITLE
[내부 정보관리팀 운영 방식] 웹진 <결> 아마존 서버 진흥원 명의의 아마존 서버로 이전

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol#13]
어제인 6월 23일 연구소가 소속되어 있는 한국여성인권진흥원 정보관리팀과 도메인 등 연구소 정보화 사업 전반에 대한 회의를 했는데요.

현재 슬로워크 cafe24 계정이 가지고 있는 웹진 <결> 도메인 명의와, 
공동체IT사회적협동조합이 가지고 있는 웹진 <결> 아마존 서버 명의를 모두 진흥원 명의로 이전해야 한다고 합니다.

특히 아마존 서버 명의 이전 건은 아직 진흥원이 아마존 계정을 가지고 있지 않은 상황인데요.
아마존 서버의 명의 이전 절차를 밟기 위해 어떤 자료가 필요한지 알려달라

>> 20kyeol05@durumi.io 로 등록되어 있는 AWS 계정을 진흥원으로 넘긴다 ?
>> 카드정보나 관련 정보도 넘겨야 한다는 부분은 전화상으로 전달했음.

**Comment by mozodev** [comment]
제가 알기로는 계정 옮기는 건 안되고요
진행원이 아마존 계정 만들면 거기로 이전해야 합니다.

**Comment by woonjjang** [comment]
좀 불필요한 미팅이어서, 관련된 가이드만 전달할께요 ~
