### ISSUE TITLE
현재 결 아마존 서버 스펙 전달하기

### ISSUE THREAD

**Issue by mozodev** [team-durumi/kyeol#14]
```
1. 아마존 서버 임대비가 월 얼마씩 지출되고 있는지, 
2. 현재 아마존에서 대여하고 있는 웹진 <결> 서버의 스펙이 어떤지, 
3. 그리고 서버 백업 주기가 어떻게 되는지
```

## 1. amazon ec2 서버 이용료 (1년간 무료)

- 개설일: 2020. 5. 6 ~ 프리티어 만료일: 2021. 5.5
- 프리티어 소개 https://aws.amazon.com/ko/ec2/pricing/
> AWS 프리 티어에는 1년 동안 매달 사용할 수 있는 750시간의 Linux 및 Windows t2.micro 인스턴스가 포함되어 있습니다. 프리 티어를 계속 유지하려면 EC2 마이크로 인스턴스만 사용하십시오

## 2. amazon ec2 spec
- 서버 종류 https://aws.amazon.com/ko/ec2/instance-types/
- t2.micro (1 cpu, 1GB ram, SSD 30gb )

## 3. 백업 주기
정기 작업이 아니라 월 유지보수 작업 시 사용자 업로드 파일, 디비를 백업하고 있음. (월 1~3회)

**Comment by woonjjang** [comment]
몇 자 보태서 전달했음. 
관련해서 저는 수요일에 연구소에 다녀올께요. ^^ (서버관련 부분인데, 그냥 지난한 얘기일 것으로 보여 저만 다녀오겠습니다. )
