### ISSUE TITLE
[서버이전] EC2(durumi-kyeol) -> EC2(가비아)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol#15]
[정보관리팀]
- 아카이브와 같은 사이트와 보이게 할 수 있지 않는가 ?
- 아카이브 814의 서브도메인으로 연결하고 넣을 수 있지 않은가 - 가능하다. 
- kyeol.archive814.kr

[기존에 유지하는 것과 아닌 것을]
- 13.97$  / 트래픽 비용 별도 / 유지보수 20만원
- (가비아)1. Linux t2.micro 30GB 기준 월 13.97$ + 트래픽 비용 별도
- (가비아)2. Linux t2.micro 30GB 기준 월 13.97$ + 트래픽 비용 별도 + 20만원(가비아 매니지드 서비스)
- 전화통화를 통해서 확인해 본 봐 가비아 매니지드 서비스도 별로 뭘 해주는게 없다고 함. 

[일정]
- 계약 관련 문제가 해결이 되면 바로 서버를 옮기실 계획이다.

**Comment by woonjjang** [comment]
[공부하면서 서버를 이전해 본다.]
1. 서버를 옮기며, 기본적인 공부를 한다. 
2. 이전이 완료되면, 별도 테스트 계정을 만들어서 directUs까지 설치해서, 냉전평화센터 아카이브쪽 directUs Testbed를 만들어 본다.

https://docs.google.com/document/d/12wz-k2FKLC2uqPD4Uc7RLOKwemsUgDyCHY-BXcWTPbE/edit#

**Comment by woonjjang** [comment]
@sunparty 점심먹고, 드라이브를 도와주실 수 있으세용 ?

**Comment by woonjjang** [comment]
http://ec2-3-34-25-166.ap-northeast-2.compute.amazonaws.com/
- @sunparty 도움을 받아서 오늘자 DB 이동 및 이전 / 입수 / mariadb 문제 해결
- 현재 rsync로 data/kyeol/files 와 data/kyeol/private 폴더를 옮기고 있습니다. (mac을 우회하면 한글 깨진다는 문제는 리눅스로 옮긴이후에 처리해 보려고 합니다. 
- @mozodev 메인에 보면 불러와지지 않는 모듈과 파일들이 있는데 파일 접근 문제인데, 도움 부탁드립니다. 

------

전체 라이브된 것을 잘 확인한 이후에 남은 작업을 하려고 합니다. 한땀한땀 하는데 모르는 것이 많네요. 
- 이전 결정된 날짜에
- 소스 / 데이터이동 / 파일 이동

**Comment by mozodev** [comment]
우선 예상대로 동작하지 않으면 오류의 원인을 파악해야 문제를 해결할 수 있겠죠

한 가지는 제가 금요일에 수정했는데
http://ec2-3-34-25-166.ap-northeast-2.compute.amazonaws.com/admin/config/media/file-system
파일 시스템 권한 문제가 있어서 css, js 빌드한 파일을 저장해야하는데 임시 디렉토리에 쓸 수 있는 권한이 없어서 발생했던거라
public, private, tmp 디렉토리에 아파치 웹서버가 파일을 쓸 수 있도록 조치해서 해결했습니다.

http://ec2-3-34-25-166.ap-northeast-2.compute.amazonaws.com/admin/reports/status
드루팔은 관리자로 로그인 후 위의 상태 보고에 가면 각종 문제를 확인할 수 있습니다.

```
오류 | Zencoder library | cURL extension must be enabled.
```

일단 이 이슈를 해결하면 
```
ubuntu@ip-10-50-11-11:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

install php7.3 curl on ubuntu 20.04
요렇게 검색해서
https://www.cloudbooklet.com/how-to-install-php-7-3-on-ubuntu-18-04/
이 문서를 찾았는데 문서 중간에
```
sudo apt install php7.3-extension_name
```
이런게 있네요 ㅎ
그리고 php extension이 로드되었는지 확인하는 방법은 phpinfo 화면에 나와있는데
웹브라우저에서 보는 화면은 보안상 하면 안되는거죠.. 나 이런거 쓰고 있어 이렇게 모두에게 알리는거니까요?
터미널에서 아래..

```
$ php -v  # 버전
$ php -m  # 사용 중인 익스텐션 목록 php -m | grep curl 해서 curl이 나오면 잘 된거죠...
$ sudo service php7.3-fpm status
$ sudo service php7.3-fpm reload
$ php -m 
```

현재 php-fpm 서버가 실행 중이고 그 앞에 아파치 웹서버가 리버스 프록시로 해당 서버와 통신하고 있는 상황입니다.
새로 php 익스텐션을 설치하고 나면 php-fpm 서버를 재시작해야 전에는 정상적으로 로드가 되더라고요..

**Comment by mozodev** [comment]
그리고 이미지 깨지는 것 관련해서 확인해봤는데
```
# symbolic link
/var/www/html/kyeol/sites/default/files => /data/kyeol/files
/var/www/html/kyeol/sites/default/private => /data/kyeol/private

public => /data/kyeol/files/files/files/
private => /data/kyeol/private/private/private/backup_migrate/
```
여기 까지 내려가야 실제 이미지 파일이 있더라고요. rsync 할 때 뭔가 잘못된듯... ㅎ
이런 문제 때문에 로컬에서 vagrant로 충분히 테스트를 해보고 진행하는게 좋습니다.

http://ec2-3-34-25-166.ap-northeast-2.compute.amazonaws.com/admin/config/media/file-system
심볼릭 링크도 필요없고 사실 이 관리화면에서 각각 이렇게 지정해주면 되겠죠 ㅎ
- /data/kyeol/files (아 이건 public 이니까 - 웹루트아래 있어야함... 심볼릭 링크 필요함)
- /data/kyeol/private

**Comment by woonjjang** [comment]
모조님 피드백 감사해요. 
학습 시간이 조금 더 걸리니, 확인하고 내일 또 여쭤 볼께요.

**Comment by mozodev** [comment]
```bash
$ sudo service mysql status
● mariadb.service - MariaDB 10.3.22 database server
     Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-07-27 14:27:15 KST; 6h ago
....
/usr/sbin/mysqld: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory
...

$ sudo journalctl -xe
...
Jul 27 21:34:04 ip-10-50-11-11 audit[2793]: AVC apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/etc/ld.so.cache" pid=2793 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=113 ouid=0
Jul 27 21:34:04 ip-10-50-11-11 audit[2793]: AVC apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/usr/lib/x86_64-linux-gnu/liblz4.so.1.9.2" pid=2793 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=11>
Jul 27 21:34:04 ip-10-50-11-11 audit[2793]: AVC apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/usr/lib/x86_64-linux-gnu/liblz4.so.1.9.2" pid=2793 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=11>
Jul 27 21:34:04 ip-10-50-11-11 mysqld[2793]: /usr/sbin/mysqld: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory
...
```

https://stackoverflow.com/questions/46111723/usr-sbin-mysqld-error-while-loading-shared-libraries-liblz4-so-1-cannot-open

- https://ko.wikipedia.org/wiki/AppArmor
-  https://sarc.io/index.php/mariadb/1416-ubuntu-mariadb-apparmor

**Comment by woonjjang** [comment]
개념이해 : https://sarc.io/index.php/mariadb/1416-ubuntu-mariadb-apparmor
```
sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld```

명령어 적용후 같은 방식으로 reboot 해도 apache2, php7.3-fpm, mariadb Status on

**Comment by woonjjang** [comment]
http://ec2-3-34-25-166.ap-northeast-2.compute.amazonaws.com/admin/reports/status
- Zencoder library 문제 해결
- pecl uplodprogress 설치해 봄 https://www.drupal.org/node/2754637

**Comment by woonjjang** [comment]
[승인씨 공유]
1차 이전 - 잘 진행되면 주말내에 진행 보고
혹시라도 문제가 생기면 월 - 화 진행 / 이전 완료 보고는 다음주 수요일 (08/05)

**Comment by woonjjang** [comment]
@mozodev 금,토,일 함께 드라이브할 시간을 지정해주시면 감사하겠습니다. 
저는 그 전까지 기존에 했던 항목들 점검하고 있겠습니다.

**Comment by mozodev** [comment]
서버 이전 관련한 건가요? 이건 끝난거 아니에요?

**Comment by woonjjang** [comment]
확인 안 된 몇 가지들도 있고, 어떤 상태인지 모르는 것들도 있어서 그냥 끝내면 안 될 것 같아서요.

**Comment by woonjjang** [comment]
2020년 7월 31일 작업 
- https://docs.google.com/document/d/12wz-k2FKLC2uqPD4Uc7RLOKwemsUgDyCHY-BXcWTPbE/edit#heading=h.26lo01633ul5

**Comment by woonjjang** [comment]
이전을 완료하였습니다. 
서버 이전은 맡아서 할 수 있도록 더 배워보겠습니다.
