### ISSUE TITLE
[메인] 영문웹진 시안 준비 HTML (09.25~)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol#19]
[국문페이지에서]
- 영문페이지로 변경 버튼 클릭하면 영문 메인

[구성]
- '일본군'위안부 소개글 / '일본군'위안부 소개 카테고리로 이동
- 메인페이지에서 카테고리를 모두 확인할 수 있도록 레이아웃 디자인을 하고 싶다. 
- 국문 페이지 레이아웃 가운데 부분에 (연구소 소개, 웹진 결 소개 / '일본군'위안부 정의 소개 및 설명
- 뉴스레터 빠짐

**Comment by woonjjang** [comment]
[screencapture-file-Users-woonjjang-dev-kyeol-en-html-en-00-main-html-2020-09-03-18_48_10.pdf](https://github.com/team-durumi/kyeol/files/5167688/screencapture-file-Users-woonjjang-dev-kyeol-en-html-en-00-main-html-2020-09-03-18_48_10.pdf)

**Comment by woonjjang** [comment]
(04505) 4th Floor, Central Place, 50 Seosomun-ro, Jung-Gu, Seoul.
Copyright 2020 Webzine by the Research Institute of Japanese Military Sexual Slavery (RIMSS) 
All Rights Reserved.

Publisher: Research Institute of Japanese Military Sexual Slavery (RIMSS)
Design: SlowWalk  Production: 별일사무소 
Editor: Sora KIM, 
Enquiries: remember814@stop.or.kr

**Comment by woonjjang** [comment]
[회의 시작되면 여기에 메모 좀 부탁해요-웹디자인 부분 의견] @sunparty

**Comment by suncrud** [comment]
로고 
* 영문로고에 ‘결' 한글이 로고처럼 보였으면 한다. 
* 결 KYEOL [연구소명] - 병렬되어있는 로고가 맘에 듬.
* 영문 KYEOL 의 폰트가 세로로 너무 좁은거 같다. (장평)
* 한글의 ‘결' 로고와 영문의 KYEOL 이 색깔이 너무 유사하다. (3동그라미 로고의 색깔차이대로 각 글자의 폰트 색깔을 다르게? )
* 각 글자의 장평 variation을 보고 싶다. 

메인 화면 
* 슬라이드 유지, 인트로의 3개 카드요소도 유지
* 인트로카드와 슬라이드가 겹치지 않는 버젼도 좋음.. 
* page header: WEBZINE KYEOL 대문자로 통일 

폰트
* 원하시는 폰트가 있으시면 영문사이트 레퍼런스를 달라

후속
* 메인페이지 2종류와 폰트 볼 수 있는 페이지 URL 혹은 문서/ 이미지 파일 전달.

**Comment by woonjjang** [comment]
- 3차 중간보고 전 자료로 퍼블리싱 목록과 디자인 시안 : https://github.com/team-durumi/kyeol-en
 - 공유 링크 : http://kyeol-en.durumi.io/index.html

**Comment by woonjjang** [comment]
우와 ! (3차)
- http://kyeol-en.durumi.io/
