### ISSUE TITLE
[국문] 전문용어 목록 페이지 / 세부(신규)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol#3]
- 전문용어(2019년도에 작업해 놓은 118개가 있음. 인물정보 36개)
- 전문용어 보이는 페이지
- 전문용어 목록 페이지

**Comment by woonjjang** [comment]
(4.17) 승인씨랑 잠깐
- 기존에는 팝업창 정도로 작성하고 있음. (그대로 사용) / cavac note
<img width="698" alt="스크린샷 2020-05-21 오후 5 00 19" src="https://user-images.githubusercontent.com/6022883/82639001-d1ceff80-9c42-11ea-9045-c60626fe6a53.png">

- 전문용어(Taxonomy) 필드(제목 / 요약필드 / 전문필드)를 만들어서 node 세부에서는 제목 . 요약필드를 불러와서 추가해 줄 수 있도록 한다. 
-- 요약필드 생성(실서버) http://www.kyeol.kr/admin/structure/taxonomy/terms/fields/field_summary
- 엮어보기 하위 메뉴로 전문용어 목록이 나오고 같은 필드로 노출되는 방식으로 간다. (엮어보기 필자, 주제처럼 나오면 됨.)

**Comment by woonjjang** [comment]
[모듈]
- 전문용어를 지정해서 추가해 주는 모듈을 사용한다.
- 해당 글에서 전문용어 일치하는게 있으면 모두 변경되어 보여준다. 

[편집화면에서]
1. http://kyeol.kr/node/180 콘텐츠에 포함되어 있는 "고노담화" 라는 단어 2개가 cavac 노트로 작성되어 있음. 
2. 위쪽 글을 "링크입력 - 고노담화를 찾아서 연결했음. "http://www.kyeol.kr/admin/structure/taxonomy/terms"
3. 편집창에서 / 보기화면에서 스타일이 cavac 노트랑 동일하게 노출되면 될 듯 함. 
4. 변경완료되면 http://www.kyeol.kr/node/166 콘텐츠에 포함되어 있는  "고노담화"도 변경해서 고객에게 전달하며 됩니다. 

[보기화면에서]
- 지정된  태그가 있는 경우 " 관련인물 -태그1, 태그2" / "관련지역 - 태그1, 태그2" 노출영역이 있다. 
- "전문용어 - 태그1, 태그2" 라고 노출되는게 필요함.

[별도화면]
- http://www.kyeol.kr/archive/location 엮어보기 화면에 인물, 주제, 지역 아래에 "전문용어" 넣고 동일하게 ㄱ ~ ㅎ 순서대로 뿌려주는 화면이 추가되면 됩니다.

**Comment by mozodev** [comment]
https://www.drupal.org/project/autotag 테스트
allowing a vocabulary to be searched against for suggestions of terms related to the content of a node.

https://www.drupal.org/node/347239

**Comment by woonjjang** [comment]
@mozodev 승인씨께 요거 회신 해 줘야할 것 같은데, 확인 좀 부탁드려요~

**Comment by mozodev** [comment]
일단 간단히 끝날 것 같지는 않습니다.

1. linkit 모듈 수정해서 cavac note 처럼 보이도록 처리하고
2. 전문용어 필드에 해당 키워드를 입력한 후 저장

이렇게 해야될 것 같아요. 
일정은 다음주 월요일 확인이 좋은데 상황이 어떤지 모르겠네요.

**Comment by woonjjang** [comment]
승인씨께 요렇게 전달하면 어떨지 ?

1. 전문용어 필드에 해당 키워드를 우선 입력해 놓으시라. (linkit 개발로 결정했으니, 추가는 해 놔도 될 듯 하네요.)
2. 개발 부분은 시간이 좀 더 소요되서, 다음주 월요일 추가 / 변경할 수 있도록 해 보겠다.

**Comment by mozodev** [comment]
네 좋습니다.

**Comment by woonjjang** [comment]
요렇게 우선 공유를 했습니다.  ~

**Comment by woonjjang** [comment]
[전문용어-국문]
1. 전문용어 필드에 해당 키워드를 입력한다. (제목 / 본문) http://kyeol.kr/admin/structure/taxonomy/terms
2. 본문에 있는 텍스트를 적고, 저장해서 실제 전문용어에 해당되는 Term에 일치하는게 있으면, 기존과 같은 전문용어 스타일로 보여준다. (따라서 에디터창에서 별도로 추가하거나 저장할 필요는 없다.)
3. 요약하면 글만쓰고 저장하면 전문용어 팝업 모양이 노출된다. 
4. 아랫쪽에 더보기 부분을 클릭하면  #관부재판 태그 목록 화면으로 이동

[기존 적용되어 있는 cavac note를 뜯어내는 작업 필요함]
1. http://www.kyeol.kr/node/180/ 고노담화 편집창에 들어가서 cavac note로 작성되어 있던 HTML 문구를 제거하고, 해당 단어만 남겨놨음.
2. ```<span class="cavacnote" popuptext="고노 요헤이(河野洋平) 관방장관이 1993년 8월 4일 ‘위안부’ 문제에 대한 일본정부의 제2차 조사결과를 발표한 담화. 고노 담화는 일본군이 위안소 설치 및 관리, ‘위안부’ 모집 및 이송에 직·간접적으로 관여한 사실과 피해자들이 본인의 의사에 반하여 모집되었다는 사실을 인정하고, 사과와 반성을 표명했다는 점에서 의의를 가진다. 그러나 배상문제에 대해서는 1965년 청구권협정으로 해결되었다는 기존의 주장을 되풀이했다. " popuptitle="고노담화">고노담화</span>  -> 고노담화```
<img width="1157" alt="스크린샷 2020-10-22 오후 7 02 07" src="https://user-images.githubusercontent.com/6022883/96861639-51395700-149f-11eb-8ae5-46a43a92780d.png">
