### ISSUE TITLE
[kyeol] 서버이전(카페24 -> AWS)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol#5]
서버 종료 (5월 7일) 전에는 카페24 -> 두루미쪽으로 서버를 이전해야 함.

**Comment by mozodev** [comment]
@sunparty 잘 됐네요 vagrant로 연습해보고 실제 서버이전까지 직접 핸들 잡고 밟아보시죠. 제가 조수석에 앉아 있을께요 운짱도 조수석에 같이 앉아거나 운전해보시거나 ㅎㅎ

**Comment by woonjjang** [comment]
넵 저도 좋습니다.

**Comment by mozodev** [comment]
https://docs.google.com/document/d/1FgD_KqhuWOVHevGTwpZUTWk3MCVvgW1taSV7tTBHLs8/edit

**Comment by mozodev** [comment]
13.124.40.13 (elastic ip)
ssh config 에 host 변경해야함!

**Comment by mozodev** [comment]
http://www.kyeol.kr/
13.124.40.13
이전 완료~
