### ISSUE TITLE
서버 이전

### ISSUE THREAD

**Issue by mozodev** [team-durumi/kyeol#8]
> 카페24의 서버 사용기간이 5월 8일로 조만간 도래합니다. 
사용기간 만료 후에도 문제없이 사이트가 작동될 수 있도록 서버 이전을 부탁드립니다. 
아직 계약서에 도장을 찍지 않았고, 계약금을 지급하지 못했지만 저희 프로젝트 진행은 문제없이 진행될 것이니 
가능한 빨리 처리부탁드립니다. 

않았고... 못했지만... 가능한 빨리.... 재밌는 어법인....

**Comment by woonjjang** [comment]
https://github.com/team-durumi/kyeol/issues/5
